# Generated by Django 2.2.9 on 2020-01-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fogstream_studying_root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
